name = "pos-supermarket-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Binding D1 Database
[[d1_databases]]
binding = "DB"
database_name = "POS_DB"
database_id = "cbf2a8f6efb85434d3bd6760d6ea059b"

# Environment variables
[vars]
API_VERSION = "1.0"

# Secrets (set via CLI: npx wrangler secret put API_KEY)
# API_KEY akan digunakan untuk autentikasi request dari frontend

[dev]
port = 8787
